### ISSUE TITLE
Warning on installation

### ISSUE THREAD

**Issue by zayau** [sstur/draft-js-utils#11]
Possibly update draft js dependency from 0.5.0 to latest(0.7.0 as of today)?

**Comment by sweetticket** [comment]
+1

**Comment by mrlarssen** [comment]
+1

**Comment by jamesjjk** [comment]
+1

**Comment by woodcode** [comment]
+1

**Comment by feychenie** [comment]
+1 this is quite an issue here too, i cannot shrinkwrap :/

(same for draft-js-utils)

**Comment by ashraffayad** [comment]
+1

**Comment by sstur** [comment]
Sorry for the delay on this. This is now fixed.
