### ISSUE TITLE
NPM version is behind

### ISSUE THREAD

**Issue by IvanoffDan** [sstur/draft-js-utils#111]
Hi, I guess npm version is behind Github. Doubled-checked it for `draft-js-export-html`. Can you guys please update npm? Thanks

**Comment by bendersej** [comment]
Indeed, the distributed package does not support`defaultBlockTag set to null`.

The check for the `null` condition is not present as it is here on Github: https://github.com/sstur/draft-js-utils/blob/master/packages/draft-js-export-html/src/stateToHTML.js#L152

Keep up the good work, that's an excellent utils

**Comment by Calyhre** [comment]
Same problem with `draft-js-import-markdown` apparently, `1.2.1` nor `1.2.0` seems to include #98

**Comment by Casen** [comment]
Bumping this. It's been quite a long time and the npm package has still not been updated. Monorepos are also problematic for both Yarn and NPM currently, so there isn't really a good work around.

**Comment by aegyed91** [comment]
bump
