### ISSUE TITLE
Data convert issue

### ISSUE THREAD

**Issue by AieraFlyyyy** [sstur/draft-js-utils#135]
..I want to convert my own data to editorState.
And here is my code:

> **const data= {
　　　blocks: [
　{data:{},depth:0,entityRanges:[],inlineStyleRanges:[],key:'13j2g',text:'',type:"unstyled"},
　{data:{},depth:0,entityRanges:[],inlineStyleRanges:[],key:'pmgo',text:' ',type:"atomic"},
　{data:{},depth:0,entityRanges:[],inlineStyleRanges:[],key:'38f7i',text:'213231213213',type:"unstyled"},
],
　　　entityMap:{0:{
type:"IMAGE",
mutability:"IMMUTABLE",
data:{src:"http://xxxxxxxxx/39e58843-70d9-efbd-417d-14c0ee2e9a2b.jpg"}}
　}
}
　let c = EditorState.createWithContent( convertFromRaw(data) )**

But when I did this: 
> 　console.log( convertToRaw( c.getCurrentContent( ) ))

the result is:

> 　blocks: [
　{data:{},depth:0,entityRanges:[],inlineStyleRanges:[],key:'13j2g',text:'',type:"unstyled"},
　{data:{},depth:0,entityRanges:[],inlineStyleRanges:[],key:'pmgo',text:' ',type:"atomic"},
　{data:{},depth:0,entityRanges:[],inlineStyleRanges:[],key:'38f7i',text:'213231213213',type:"unstyled"},
],
　　entityMap:{ }

I don't know what's going on with this..

Is anybody know that?

**Comment by betancourtl** [comment]
Not really sure why this is happening but it could be a mistake on the data object. I usually use `npm i draft-js-raw-content-state` to create editorStates without having to build them manually.

**Comment by AieraFlyyyy** [comment]
I figure out that..That's because I ignored the `entityRanges`  
`entityRanges` is used to control the Image or Link or some special text..
When I add the `entityRanges` ....everything is fine..
So I will close the issue..
