### ISSUE TITLE
No matching version found for draft-js-utils@^1.3.3

### ISSUE THREAD

**Issue by MrCox007** [sstur/draft-js-utils#171]
It was specified as a dependency of 'draft-js-export-html'

**Comment by ismaelbelghiti** [comment]
Hi, I have the same problem so I cannot deploy anymore. Btw really good lib !

**Comment by imsobear** [comment]
+1

**Comment by passportradio** [comment]
How to avoid such sudden breakdowns in the app? Constantly breaking down something in the dependencies...

**Comment by inder-miracle** [comment]
We also facing same issue, there is no draft-js-utils@^1.3.3 version exist in repository, where they found this version number

**Comment by acpplife** [comment]
`draft-js-import-html@1.2.1 › draft-js-import-element@1.3.3 › draft-js-utils@^1.3.3`
draft-js-utils@^1.3.3 not found
How to solve this?hurry...

**Comment by prachikarekar** [comment]
yes we are facing the same issue

npm ERR! notarget No compatible version found: draft-js-utils@^1.3.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.3.2, 1.3.0, 1.2.4, 1.2.0, 1.1.0, 1.0.2, 1.0.1, 0.2.0, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'draft-js-export-html'
npm ERR! notarget

**Comment by ayoubyoub** [comment]
same issue 👎 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for draft-js-utils@^1.3.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'draft-js-export-html'

**Comment by TheWWWorm** [comment]
try adding

```
"resolutions": {
    "draft-js-utils": "1.3.2"
}
```

to your package.json

**Comment by ayoubyoub** [comment]
3 hours ago  => v1.3.3 changed in all package.json.
resolutions can be the solution but we need to know why this change and having the best solution :)

**Comment by bhovhannes** [comment]
@sstur it seems that v1.3.3 version of `draft-js-utils` is missing from npm registry.
Latest published version is 1.3.2.
Can you publish missing version? This is blocking our CI.

**Comment by akifd** [comment]
Or downgrade the dependency to 1.3.2.

**Comment by acpplife** [comment]
I only use `"draft-js-import-html": "^1.2.1"`,it has dependency to ` draft-js-import-element@1.3.3`
how to fix that unless publish a new package?

`Error: [draft-js-import-html@1.3.3 › draft-js-import-element@1.3.3 › draft-js-utils@^1.3.3] GET https://registry.npm.taobao.org/draft-js-utils/%3E%3D1.3.3%20%3C2.0.0 response 405 status
    at get (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:51:17)
    at get.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by nileshpatwardhan** [comment]
latest version that exists for draft-js-utils is 1.3.2. looks like 1.3.3 is missing in the repo
We are facing the issue
**3549 verbose stack draft-js-utils: No matching version found for draft-js-utils@^1.3.3**
please publish the new version.

**Comment by insidero** [comment]
Please update!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by passportradio** [comment]
How to fix it temporarily?

**Comment by akifd** [comment]
> How to fix it temporarily?

This was already answered above:

> Add
> 
> ```
> "resolutions": {
>     "draft-js-utils": "1.3.2"
> }
> ```
> 
> to your package.json, it will force the download of existing version.

**Comment by charliedavison** [comment]
@User3759685 Isn't that only an option if you're using Yarn?

**Comment by insidero** [comment]
Adding the resolution didn't work for me. Is there any other workaround?
P.S: Im using npm

**Comment by canpolatoral** [comment]
Omg! A huge mistake...

if you add this dependencies in your package.json, it works...

 "draft-js-export-html": "1.3.2",
 "draft-js-export-markdown": "1.3.2",
 "draft-js-import-element": "1.3.2",
 "draft-js-import-html": "1.3.2",
 "draft-js-import-markdown": "1.3.2",
  "draft-js-utils": "1.3.2",

**Comment by rajeev-k-tomy** [comment]
@canpolatoral This solution is not working for me. I am using `npm` only. Not `yarn`.

**Comment by canpolatoral** [comment]
@progammer-rkt I am not using yarn. I am using npm, too. And it's working for me.

**Comment by rajeev-k-tomy** [comment]
@canpolatoral adding every dependency you have mentioned work for me. In my case, the console yelled only about the `draft-js-import-element` package. So I only added 3 of the package dependency provided above. Adding every package as shown above resolved the error for me. Thank you.

**Comment by canpolatoral** [comment]
@progammer-rkt exactly, you need to add all the packages.

**Comment by sstur** [comment]
This has been fixed. Thanks for bringing it to my attention!
