### ISSUE TITLE
1.4.0 published package is missing typings 

### ISSUE THREAD

**Issue by petyosi** [sstur/draft-js-utils#193]
https://unpkg.com/browse/draft-js-export-html@1.3.3/
VS 
https://unpkg.com/browse/draft-js-export-html@1.4.0/

**Comment by sibelius** [comment]
do you want to help us migrate to typescript https://github.com/sstur/draft-js-utils/issues/192

this could fix this

**Comment by TrySound** [comment]
Sorry for that. Published 1.4.1

**Comment by Jtfinlay** [comment]
Are they still missing for draft-js-import-markdown 1.4.0?
