### ISSUE TITLE
Whitelines being stripped

### ISSUE THREAD

**Issue by SamSimmons** [sstur/draft-js-utils#194]
Hi there, I'm having trouble with newlines not being respected to when being converted from markdown. If I have a string of markdown like `the quick \nbrown fox` I'm expecting the editor to look like 

![Screen Shot 2019-08-01 at 12 12 16 PM](https://user-images.githubusercontent.com/14170458/62256734-91558980-b456-11e9-9637-f07da84c4559.png)

but getting (ignore the color difference)

![Screen Shot 2019-08-01 at 12 12 33 PM](https://user-images.githubusercontent.com/14170458/62256737-97e40100-b456-11e9-9eff-113b99d6667d.png)

When I enter the text manually it works as expected, it's only when converting from saved markdown. So I'm thinking the bug may lie in the conversion. Happy to provide any more details, that may help in figuring this out. 

I'm using the markdown to initialize the editor like `EditorState.createWithContent(initialContent)` where initialContent is `the quick \nbrown fox`

**Comment by sstur** [comment]
As far as I know, the current behavior is correct. A single newline in Markdown will not result in a linebreak in the rendered output.

There is an alternative Markdown format called Github Flavored Markdown (GFM) which I think will treat a single newline as a `<br>` but GFM is not on by default, you will need to pass an option `gfm: true`.
