### ISSUE TITLE
Trailing space in style block results in misrendered markdown

### ISSUE THREAD

**Issue by ashbrowning** [sstur/draft-js-utils#208]
Within DraftJS, if I have a string such as ' foo ' styled entirely bold, exporting this to markdown will output `** foo **` which due to the surrounding whitespaces, results in `** foo **` being rendered rather than **foo**. 

[Similar issues occur](https://marked.js.org/demo/?text=**%20foo%20**%0A%0A**foo**%0A%0A**foo%20**%0A%0A*foo%20*bar%0A%0A*%20foo*%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.8.0) when the whitespace is only on one end of the string.

I'm thinking that such styled strings should be trimmed and any whitespace be pushed to outside of the formatting syntax such that it can be rendered correctly. I can push a PR up shortly.

**Comment by jjjjeeffff** [comment]
According to the [CommonMark spec](https://spec.commonmark.org/0.29/#example-377) you are correct.

**Comment by sstur** [comment]
Yes, you're correct, that certainly is a bug.

I'm not confident I'd be able to land a fix for this in a timely fashion, so any PR would be welcome from either you or from the community.

**Comment by jjjjeeffff** [comment]
It looks like @ashbrowning has https://github.com/sstur/draft-js-utils/pull/209 open to address.
