### ISSUE TITLE
Markdown Italic does not work with word selected in middle

### ISSUE THREAD

**Issue by joaoBernado** [sstur/draft-js-utils#251]
The markdown for italic does not work in the scenario:

aaaaa _bbbbb _ccccc"

After we save this änd try to read in the Rich Text editor the word "bbbbb" will not show in italic instead it will show "_bbbbb _".

Is there any support on this project... will a merge request be accepted if we provided a viable solution?

**Comment by MSGInsurIt** [comment]
@sstur we have added created the PR

https://github.com/sstur/draft-js-utils/pull/254
