### ISSUE TITLE
No support on IE9

### ISSUE THREAD

**Issue by Rahulgarg30591** [sstur/draft-js-utils#44]
I guess there is no support for stateFromHTML on IE9. Please check. @sstur.

**Comment by sstur** [comment]
IE9 and below is not supported and I haven't tested this code on it. Support is not planned for anything older than IE10 or any browser with less than 1% global usage.

**Comment by Rahulgarg30591** [comment]
sir @sstur, do you know any good way to convert html to state for IE9 ?

**Comment by sstur** [comment]
I do not really know. I have not developed for legacy IE in some time and I'm not sure what are the limitations of that browser that prevent this from working. I imagine this code could probably be made work with IE9 with some amount of debugging effort.

I'm not even sure if Draft will support IE9.

**Comment by Rahulgarg30591** [comment]
Draft is working quite good in IE9. Its the DOM parser which is used inside the stateFromHTML which doesn't accept parseFromString(string, 'text/html') format inside IE9.

Polyfill for parseFromString for text/html doesn't help either. InnerHTML property of a DOM element is a readonly on IE9.
