### ISSUE TITLE
Options Blockrenderers

### ISSUE THREAD

**Issue by ferdiemcdaniel** [sstur/draft-js-utils#45]
``` js
export const LFEditor = ({ editorState }) => {

  let options = {
    blockRenderers: {
      ATOMIC: (block) => {
        const type = contentBlock.getType();
        if (type == 'atomic') {
          return `<div>hello world</div>`;
        }
        return null;
      }
    }
  };
  let html = stateToHTML(editorState.getCurrentContent(), options);
  return <div dangerouslySetInnerHTML={_createMarkup(html)} />;
};
```

Unfortunately the returned hrml string doesn't contain the blocks supposedly mark up.

**Comment by sstur** [comment]
I don't think you need to check the `type == 'atomic'` since it will only execute that function if the type is ATOMIC.

Can you try this:

``` js
export const LFEditor = ({ editorState }) => {

  let options = {
    blockRenderers: {
      atomic: (block) => {
        return `<div>hello world</div>`;
      }
    }
  };
  let html = stateToHTML(editorState.getCurrentContent(), options);
  console.log('>>> HTML:', html);
  return <div dangerouslySetInnerHTML={_createMarkup(html)} />;
};
```

...and let me know what you see in the console?

(Edited 2016-11-02T14:08:33.463Z to lowercase `atomic`)

**Comment by mikejoseph** [comment]
@ferdiemcdaniel I was having a similar issue - but I changed `ATOMIC` to `atomic` and it works as expected.

I think that may just be a documentation issue? Because the value of Block.getType() is all lower case, afaik.

**Comment by sstur** [comment]
Oh, I'll edit the example. Thanks @mikejoseph.
