### ISSUE TITLE
React-DOM is no longer  "secretly" included in React > 15.4.0 (CSSProperty require from react = error)

### ISSUE THREAD

**Issue by orditeck** [sstur/draft-js-utils#51]
Since [release 15.4.0](https://github.com/facebook/react/releases/tag/v15.4.0), React package and browser build no longer "secretly" includes React DOM.

Resulting in

```
Failed to compile.

Error in ./~/draft-js-export-html/lib/helpers/styleToCSS.js
Module not found: 'react/lib/CSSProperty' in /Users/orditeck/Sites/MyProject/frontend/node_modules/draft-js-export-html/lib/helpers

 @ ./~/draft-js-export-html/lib/helpers/styleToCSS.js 7:19-51
```

Coming [from this line](https://github.com/sstur/draft-js-export-html/blob/master/src/helpers/styleToCSS.js#L3), `var _CSSProperty = require('react/lib/CSSProperty');`

I'll open a pull request in a few minutes.

**Comment by andrew-culver** [comment]
From this morning's React blog post:

> However, there is a possibility that you imported private APIs from react/lib/*, or that a package you rely on might use them. We would like to remind you that this was never supported, and that your apps should not rely on internal APIs. The React internals will keep changing as we work to make React better.

Here is the terminal error:

> ERROR in ./\~/draft-js-export-html/lib/helpers/styleToCSS.js
> Module not found: Error: Cannot resolve module 'react/lib/CSSProperty' in /p4workspaces/aculver_ilivdesktop05_iliv-composer_main/node_modules/draft-js-export-html/lib/helpers
>  @ ./~/draft-js-export-html/lib/helpers/styleToCSS.js 7:19-51

**Comment by orditeck** [comment]
@andrew-culver yep exactly. I opened a pull request, waiting for @sstur to merge 😄

**Comment by stevensacks** [comment]
You're going to wait a long time. This project is basically abandoned. Check out https://github.com/HubSpot/draft-convert

**Comment by sstur** [comment]
@orditeck, Thanks for the PR!

**Comment by sstur** [comment]
@orditeck's fix has been published to npm now.

**Comment by dimafeng** [comment]
The PR breakes typescript support.

Typescript compiler says: 
```
ERROR in ./~/draft-js-export-html/lib/helpers/styleToCSS.js
Module not found: Error: Cannot resolve module 'react-dom/lib/CSSProperty' in /Users/fundcount/Documents/dev/workspaces/community/client/node_modules/draft-js-export-html/lib/helpers
 @ ./~/draft-js-export-html/lib/helpers/styleToCSS.js 7:19-55

```

I believe this is somehow related to the fact that [the latest typings for react](https://www.npmjs.com/package/@types/react) are for v0.14.
Any idea how this could be solved with these old typings?

**Comment by dimafeng** [comment]
Taking into account #55, my error may be caused by the actual react version which is 15.2.1
