### ISSUE TITLE
Cannot resolve module 'react-dom/lib/CSSProperty'

### ISSUE THREAD

**Issue by dmt0** [sstur/draft-js-utils#55]
Getting this error after installing 0.5.2:

```
ERROR in ./~/draft-js-export-html/lib/helpers/styleToCSS.js
Module not found: Error: Cannot resolve module 'react-dom/lib/CSSProperty' in /Users/dmt0/projects/web/node_modules/draft-js-export-html/lib/helpers
 @ ./~/draft-js-export-html/lib/helpers/styleToCSS.js 7:19-55
```

**Comment by SomethingSexy** [comment]
It seems to running fine for me if you are on react/react-dom@15.4.0

**Comment by dmt0** [comment]
OK, just found this: https://github.com/sstur/draft-js-export-html/issues/51

**Comment by sstur** [comment]
Oops, we should not break on React 15.3. This is a bug.

**Comment by brycedorn** [comment]
+1, I'm on react/dom 15.4.0 but getting this error

**Comment by smtheard** [comment]
This actually still breaks on 15.4 for me as well. I might be doing something wrong but I can't seem to get it to work.

**Comment by jundl77** [comment]
Yeah same issue here, and I'm on react version 15.3.1 (and unfortunately I can't updated because of other dependencies that require 15.3.1). It would be awesome if this  would work.

**Comment by levbrie** [comment]
See #51 and if you still have problems it may be that you need to also install [react-dom](https://www.npmjs.com/package/react-dom)

**Comment by ilyamkin** [comment]
I'm getting this error after upgrading react and react-dom to 16.0.0-beta.5 version.

As has been said here: https://github.com/facebook/react/issues/10294

> There is no react/lib/* and react-dom/lib/* anymore. Even in CommonJS environments, React and ReactDOM are precompiled to single files (“flat bundles”). If you previously relied on undocumented React internals, and they don’t work anymore, let us know about your specific case in this issue, and we’ll try to figure out a migration strategy for you.

**Comment by Radivarig** [comment]
If you want to hack it until it gets fixed you can go to `node_modules/draft-js-export-html` and do `npm i react-dom`

**Comment by Radivarig** [comment]
If you want to use it before it gets fixed you can do `npm i react-dom` from inside of `node_modules/draft-js-export-html` folder.
