### ISSUE TITLE
WARNING: DraftEntity.get will be deprecated soon! Please use "contentState.getEntity" instead.

### ISSUE THREAD

**Issue by gbbr** [sstur/draft-js-utils#67]
Related to https://github.com/sstur/draft-js-import-element/issues/31

This should be an easy fix.

**Comment by gbbr** [comment]
I can start work on this - is this project still being maintained?

**Comment by mikaelwaltersson** [comment]
Just created a PR for the fix

**Comment by quicksnap** [comment]
Doesn't seem to be any activity on this repo in a while.. is it unmaintained? Is there an active fork anywhere?

**Comment by quicksnap** [comment]
Perhaps: https://github.com/jpuri/draftjs-to-html
