### ISSUE TITLE
Where can I find a minified version?

### ISSUE THREAD

**Issue by Dagur** [sstur/draft-js-utils#72]
Hi

I'm not using node. Where can I download a .min.js version of this library?

Thanks,
Dagur

**Comment by oleksandr-kuzmenko** [comment]
@Dagur, hi!
I think, at the moment there is no minified version.
But I think you can use a service like https://unpkg.com

**Comment by sstur** [comment]
Thanks @alxpy. That is correct, there is no minified version published on npm.
