### ISSUE TITLE
How can i get my iframe tags converted ?

### ISSUE THREAD

**Issue by jackmatrix** [sstur/draft-js-utils#74]
Now it is possible to add embedded youtube content in draft js editor by using the draft js video plugin. 
However, draft-js-export-html seems to ignore iframe tags.
All iframes are converted into 

`<figure>&nbps</figure>`

It's very annoying, i really need to "stringify iframes "
Is there a tips to turn  iframe tags into string html ?

Thanks for your support

**Comment by sponia-joker** [comment]
Is there any solutions?thanks

**Comment by volkandkaya** [comment]
Was this solved?

**Comment by volkandkaya** [comment]
@jackmatrix @sponia-joker did you solve it?

**Comment by mkhotib21** [comment]
hello, is there any updates ? my iframe in html string is not parsed to block, it always return null entity key, so that it can't reach condition with my iframe decorator thank you
