### ISSUE TITLE
Please update NPM module.

### ISSUE THREAD

**Issue by Cplantijn** [sstur/draft-js-utils#77]
Can you please upgrade the NPM module to resolve the 

```
WARNING: DraftEntity.get will be deprecated soon!
Please use "contentState.getEntity" instead.
```

deprecation warning? This was fixed in this pull request https://github.com/sstur/draft-js-export-html/pull/71 which was merged into master

**Comment by leanazulyoro** [comment]
I need this too! just "npm publish" please

**Comment by sstur** [comment]
Done.

Sorry about the delay on that.
