### ISSUE TITLE
Underline should use the `u` tag instead of `ins`

### ISSUE THREAD

**Issue by asterite** [sstur/draft-js-utils#78]
`draft-js` [uses the `u` tag](https://github.com/facebook/draft-js/blob/213cd764f61cc64552bddd672ae1748529d55333/src/model/encoding/convertFromHTMLToContentBlocks.js#L70) in the `convertFromHTML` function. Because `draft-js-export-html` uses `ins`, when you export to HTML and then convert back from HTML you loose the underline information. I suggest to use `u` instead.

**Comment by sstur** [comment]
I'll be open to a PR for this.

**Comment by sstur** [comment]
This is now fixed in master. Will publish soon.
