### ISSUE TITLE
Import as show in readme not working

### ISSUE THREAD

**Issue by kristinn93** [sstur/draft-js-utils#80]
Hi, awesome project ✌️

I'm unable to import stateToHtml with the following

```javascript
import {stateToHTML} from 'draft-js-export-html';
console.log(stateToHtml) // undefined
```

However if I import it like this it works
```javascript
import stateToHtml from 'draft-js-export-html/lib/stateToHTML';
console.log(stateToHtml)
// function stateToHTML(content, options) {
//   return new MarkupGenerator(content, options).generate();
// }
```

```json
"webpack": "^2.2.0"
node -v // v7.7.3
cat node_modules/draft-js-export-html/package.json | grep version //"version": "0.5.4"
yarn --version // 0.22.0
macOS Sierra v 10.12.4
```

Do you have any idea why, all help is appreciated ?

**Comment by benbonnet** [comment]
i might be wrong, but you're not passing the state, aren't you ?

the README does shows the following :

```
import {stateToHTML} from 'draft-js-export-html';
let html = stateToHTML(contentState);
```

`contentState` being in your onchange event, to which you pass your editor' state

Minimal example : 

```
class Text extends React.Component {
  onChange = (editorState) => {
    this.setState({ editorState })
    console.log(stateToHTML(editorState.getCurrentContent()))
  }
  focus = () => {
    this.editor.focus();
  }
  render() {
    return(
      <Editor
        editorState={this.state.editorState}
        onChange={this.onChange}
      />
    )
  }
}
```

**Comment by kristinn93** [comment]
@deesx thanks for the reply, been a while since I looked at this but if I remember correctly the only part that was failing was the import statement, I got this working by importing `draft-js-export-html/lib/stateToHTML` which resolve to `draft-js-export-html/lib/stateToHTML.js`

This might be some problem with my `babel` or `webpack` setup dealing with how it imports from  `draft-js-export-html/lib/main.js`
