### ISSUE TITLE
could it support 'inlineStyleFn'

### ISSUE THREAD

**Issue by focus0802** [sstur/draft-js-utils#82]
There are some inline styles like 'fontSize'-'color'-'backgroundColor' that I want to set.
Here is `customStyleFn` that I used in Draft Editor Component:
```javascript
this.customStyleFn = (style) => {
      const output = {};
      let fontSize = style.filter(value => value.startsWith('fontSize_')).first();
      if (fontSize) {
        fontSize = fontSize.replace('fontSize_', '');
        output.fontSize = fontSize;
      }
      let color = style.filter(value => value.startsWith('color_')).first();
      if (color) {
        color = color.replace('color_', '');
        output.color = color;
      }
      let backgroundColor = style.filter(value => value.startsWith('backgroundColor_')).first();
      if (backgroundColor) {
        backgroundColor = backgroundColor.replace('backgroundColor_', '');
        output.backgroundColor = backgroundColor;
      }
      return output;
};
```

So, I hope the `stateToHTML` has the same option like this. Will it be added?🙂

**Comment by sstur** [comment]
You can use `blockStyleFn` or `entityStyleFn` for this.

**Comment by denich** [comment]
@sstur Can you provide an example how to use it in such case? Seems like there's no way t do it.
Basically we need support of [customStyleFn](https://draftjs.org/docs/api-reference-editor.html#customstylefn) from the draft-js Editor component.
